name: Deploy OrbitCode Frontend to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Bypass npm Bug and Force Clean Linux Install
        run: |
          cd client
          rm -rf node_modules package-lock.json
          npm install --include=optional

      - name: Build React Client
        run: |
          cd client
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # This stays 'dist' because your vite config outputs to '../dist'
          branch: gh-pages
